// src/components/ContactForm.tsx
'use client';

import { useState } from 'react';
import styles from './ContactForm.module.css';

const EMAIL = 'anchorforgedigital@gmail.com';

const PROJECT_TYPES = [
	'Standard — $200',
	'Standard Plus — $275',
	'Pro — $450+',
	'Pro Plus — $650+',
	'Max — $950+',
	'Max Plus — Custom'
];

type FieldErrors = { name?: string; email?: string; message?: string };

export default function ContactForm() {
	const [name, setName] = useState('');
	const [senderEmail, setSenderEmail] = useState('');
	const [projectType, setProjectType] = useState(PROJECT_TYPES[0]);
	const [message, setMessage] = useState('');
	const [fax, setFax] = useState('');
	const [submitted, setSubmitted] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const [error, setError] = useState('');
	const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});

	async function submitForm(event: React.FormEvent<HTMLFormElement>) {
		event.preventDefault();
		setError('');

		// Client-side validation so errors can be wired to aria-invalid
		const errors: FieldErrors = {};
		if (!name.trim()) errors.name = 'Please enter your name.';
		if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(senderEmail.trim()))
			errors.email = 'Please enter a valid email address.';
		if (!message.trim()) errors.message = 'Please tell us a little about your project.';
		setFieldErrors(errors);
		if (Object.keys(errors).length > 0) return;

		setSubmitting(true);
		setSubmitted(false);

		try {
			const response = await fetch('/api/contact', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({ name, email: senderEmail, projectType, message, fax })
			});
			const result: { error?: string } = await response.json();

			if (!response.ok) throw new Error(result.error);
			setSubmitted(true);
			setName('');
			setSenderEmail('');
			setMessage('');
			setFax('');
		} catch (requestError) {
			setError(
				requestError instanceof Error && requestError.message
					? requestError.message
					: 'We could not send your message. Please email us directly instead.'
			);
		} finally {
			setSubmitting(false);
		}
	}

	return (
		<section id="contact" className={styles.contact} aria-labelledby="contact-title">
			<div className={styles.contactContainer}>
				<div className={styles.contactCopy}>
					<span className="kicker">Start a conversation</span>
					<h2 id="contact-title">
						Not sure where to <em>begin</em>?
					</h2>
					<p>
						Tell us what your business does, what you need, and what you&rsquo;re working with.
						We&rsquo;ll help you find the right starting point.
					</p>
					<a className={styles.contactFallback} href={`mailto:${EMAIL}`}>
						Or email {EMAIL} directly ↗
					</a>
				</div>

				<form className={`${styles.contactForm} glass-medium`} onSubmit={submitForm} noValidate>
					<div className={styles.formField}>
						<label htmlFor="name">Name</label>
						<input
							id="name"
							required
							autoComplete="name"
							value={name}
							onChange={(event) => setName(event.target.value)}
							aria-invalid={fieldErrors.name ? true : undefined}
							aria-describedby={fieldErrors.name ? 'name-error' : undefined}
						/>
						{fieldErrors.name && (
							<p id="name-error" className={styles.formFieldError}>
								{fieldErrors.name}
							</p>
						)}
					</div>
					<div className={styles.formField}>
						<label htmlFor="email">Email</label>
						<input
							id="email"
							type="email"
							required
							autoComplete="email"
							value={senderEmail}
							onChange={(event) => setSenderEmail(event.target.value)}
							aria-invalid={fieldErrors.email ? true : undefined}
							aria-describedby={fieldErrors.email ? 'email-error' : undefined}
						/>
						{fieldErrors.email && (
							<p id="email-error" className={styles.formFieldError}>
								{fieldErrors.email}
							</p>
						)}
					</div>
					<div className={styles.formField}>
						<label htmlFor="project-type">Project type</label>
						<select
							id="project-type"
							value={projectType}
							onChange={(event) => setProjectType(event.target.value)}
						>
							{PROJECT_TYPES.map((type) => (
								<option key={type} value={type}>
									{type}
								</option>
							))}
						</select>
					</div>
					<div className={styles.formField}>
						<label htmlFor="message">What are you hoping to build?</label>
						<textarea
							id="message"
							required
							rows={5}
							value={message}
							onChange={(event) => setMessage(event.target.value)}
							aria-invalid={fieldErrors.message ? true : undefined}
							aria-describedby={fieldErrors.message ? 'message-error' : undefined}
						/>
						{fieldErrors.message && (
							<p id="message-error" className={styles.formFieldError}>
								{fieldErrors.message}
							</p>
						)}
					</div>
					{/* Honeypot: hidden from humans, ignored by password managers because of the neutral name */}
					<div className={styles.formHoneypot} aria-hidden="true">
						<label htmlFor="fax">Fax</label>
						<input
							id="fax"
							name="fax"
							value={fax}
							onChange={(event) => setFax(event.target.value)}
							tabIndex={-1}
							autoComplete="off"
						/>
					</div>
					<button className="btn-primary" type="submit" disabled={submitting}>
						{submitting ? 'Sending…' : 'Send project inquiry'} <span aria-hidden="true">↗</span>
					</button>
					{submitted && (
						<p className={styles.formNote} role="status">
							Message sent. We&rsquo;ll get back to you soon.
						</p>
					)}
					{error && (
						<p className={styles.formError} role="alert">
							{error}
						</p>
					)}
				</form>
			</div>
		</section>
	);
}

// src/lib/components/ContactForm.svelte
<script>
	const email = 'anchorforgedigital@gmail.com';
	const projectTypes = [
		'Standard — $200',
		'Standard Plus — $275',
		'Pro — $450+',
		'Pro Plus — $650+',
		'Max — $950+',
		'Max Plus — Custom'
	];

	let name = $state('');
	let senderEmail = $state('');
	let projectType = $state(projectTypes[0]);
	let message = $state('');
	let website = $state('');
	let submitted = $state(false);
	let submitting = $state(false);
	let error = $state('');

	async function submitForm() {
		submitting = true;
		submitted = false;
		error = '';

		try {
			const response = await fetch('/api/contact', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({ name, email: senderEmail, projectType, message, website })
			});
			const result = await response.json();

			if (!response.ok) throw new Error(result.error);
			submitted = true;
			name = '';
			senderEmail = '';
			message = '';
			website = '';
		} catch (requestError) {
			error =
				requestError.message || 'We could not send your message. Please email us directly instead.';
		} finally {
			submitting = false;
		}
	}
</script>

<section id="contact" class="contact" aria-labelledby="contact-title">
	<div class="contact-container">
		<div class="contact-copy">
			<span class="kicker">// Start a conversation</span>
			<h2 id="contact-title">Not sure where to <em>begin</em>?</h2>
			<p>
				Tell us what your business does, what you need, and what you’re working with. We’ll help you
				find the right starting point.
			</p>
			<a class="contact-fallback" href={`mailto:${email}`}>Or email {email} directly ↗</a>
		</div>

		<form
			class="contact-form glass-medium"
			onsubmit={(event) => {
				event.preventDefault();
				submitForm();
			}}
		>
			<div class="form-field">
				<label for="name">Name</label>
				<input id="name" bind:value={name} required autocomplete="name" />
			</div>
			<div class="form-field">
				<label for="email">Email</label>
				<input id="email" type="email" bind:value={senderEmail} required autocomplete="email" />
			</div>
			<div class="form-field">
				<label for="project-type">Project type</label>
				<select id="project-type" bind:value={projectType}>
					{#each projectTypes as type (type)}
						<option value={type}>{type}</option>
					{/each}
				</select>
			</div>
			<div class="form-field">
				<label for="message">What are you hoping to build?</label>
				<textarea id="message" bind:value={message} required rows="5"></textarea>
			</div>
			<div class="form-honeypot" aria-hidden="true">
				<label for="website">Website</label>
				<input id="website" name="website" bind:value={website} tabindex="-1" autocomplete="off" />
			</div>
			<button class="btn-primary" type="submit" disabled={submitting}>
				{submitting ? 'Sending…' : 'Send project inquiry'} <span aria-hidden="true">↗</span>
			</button>
			{#if submitted}
				<p class="form-note" role="status">Message sent. We’ll get back to you soon.</p>
			{/if}
			{#if error}
				<p class="form-error" role="alert">{error}</p>
			{/if}
		</form>
	</div>
</section>

<style>
	.contact {
		padding: var(--space-section) 0;
		border-top: 1px solid var(--color-border);
	}

	.contact-container {
		display: grid;
		grid-template-columns: 0.8fr 1.2fr;
		gap: var(--space-16);
		max-width: var(--page-max);
		margin: 0 auto;
		padding: 0 var(--page-padding);
	}

	.contact-copy h2 {
		margin-bottom: var(--space-5);
		font-size: clamp(2.5rem, 6vw, 5rem);
		letter-spacing: -0.03em;
	}

	.contact-copy h2 em {
		font-family: var(--font-display);
		font-weight: 400;
	}

	.contact-copy p {
		max-width: 420px;
		margin-bottom: var(--space-6);
		font-weight: 300;
		color: var(--color-text-secondary);
	}

	.contact-fallback {
		font-family: var(--font-mono);
		font-size: var(--text-xs);
		color: var(--color-text-muted);
		text-decoration: underline;
		text-underline-offset: 4px;
	}

	.contact-form {
		display: grid;
		gap: var(--space-5);
		padding: var(--space-8);
		border-radius: var(--radius-lg);
	}

	.form-field {
		display: grid;
		gap: var(--space-2);
	}

	.form-field label {
		font-family: var(--font-mono);
		font-size: var(--text-xs);
		letter-spacing: 0.06em;
		text-transform: uppercase;
		color: var(--color-text-secondary);
	}

	.form-field input,
	.form-field select,
	.form-field textarea {
		width: 100%;
		padding: var(--space-3) var(--space-4);
		border: 1px solid var(--color-border-strong);
		border-radius: var(--radius-sm);
		background: rgba(0, 0, 0, 0.25);
		color: var(--color-text);
		font: inherit;
		font-size: var(--text-base);
	}

	.form-field textarea {
		resize: vertical;
		min-height: 120px;
	}

	.form-field input:focus,
	.form-field select:focus,
	.form-field textarea:focus {
		border-color: var(--color-forge-glow);
		outline: 2px solid rgba(212, 148, 58, 0.25);
		outline-offset: 1px;
	}

	.form-note {
		font-size: var(--text-xs);
		color: var(--color-forge-hot);
	}

	.form-error {
		font-size: var(--text-xs);
		color: #ff9d9d;
	}

	.form-honeypot {
		position: absolute;
		width: 1px;
		height: 1px;
		overflow: hidden;
		clip: rect(0 0 0 0);
	}

	button:disabled {
		cursor: wait;
		opacity: 0.65;
	}

	@media (max-width: 768px) {
		.contact-container {
			grid-template-columns: 1fr;
			gap: var(--space-10);
		}
		.contact-form {
			padding: var(--space-5);
		}
	}
</style>
